### ISSUE TITLE
Can't install on my phone

### ISSUE THREAD

**Issue by muhammadarif1** [hyeongkyeong/Logi#1]
Android 5.1
Device oppo neo 5

**Comment by hyeongkyeong** [comment]
It is built on a minimum Android 4.4. But I tested only on Android 8.0 version.
Did you use this to install the app? release 0.0.2?
https://github.com/hyeongkyeong/Logi/releases/download/0.0.2/app-release.apk
What message did you see when you failed to install?

**Comment by muhammadarif1** [comment]
it say failed to install
, let me try new version

**Comment by muhammadarif1** [comment]
New version also not work

**Comment by hyeongkyeong** [comment]
There seems to be a lot of problems with the lower version. 
Sorry about that I don't have a plan to solve them yet. 
I confirmed that the Android 7 version has no problem with the installation. Please refer to it.
